--Dirty reads read uncommited/commited
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM Balls
waitfor DELAY '00:00:15'
SELECT * FROM Balls
COMMIT TRANSACTION

--non-repeatable reads commited/repeatable read
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM Balls
WAITFOR DELAY '00:00:05'
SELECT * FROM Balls
COMMIT TRANSACTION

--phantom reads repeatable read/serializable
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Balls
WAITFOR DELAY '00:00:05'
SELECT * FROM Balls
COMMIT TRANSACTION

--deadlock
SET DEADLOCK_PRIORITY high
BEGIN TRANSACTION
UPDATE Referees SET Name = 'Someone - transaction 2' WHERE Rid = 1
WAITFOR DELAY '00:00:10'

UPDATE Balls SET BallName = 'Adidas Final - transaction 2' WHERE Price = 500
COMMIT TRANSACTION